/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.data.engine.model.impl;

import com.liferay.data.engine.model.DEDataLayout;
import com.liferay.data.engine.model.DEDataLayoutModel;
import com.liferay.data.engine.model.DEDataLayoutSoap;
import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.exportimport.kernel.lar.StagedModelType;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.LocaleException;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.User;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.service.UserLocalServiceUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.LocaleUtil;
import com.liferay.portal.kernel.util.LocalizationUtil;
import com.liferay.portal.kernel.util.PortalUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.Validator;

import java.io.Serializable;

import java.lang.reflect.Constructor;
import java.lang.reflect.InvocationHandler;

import java.sql.Types;

import java.util.ArrayList;
import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Locale;
import java.util.Map;
import java.util.Set;
import java.util.TreeSet;
import java.util.function.BiConsumer;
import java.util.function.Function;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model implementation for the DEDataLayout service. Represents a row in the &quot;DEDataLayout&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface </code>DEDataLayoutModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link DEDataLayoutImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see DEDataLayoutImpl
 * @generated
 */
@JSON(strict = true)
@ProviderType
public class DEDataLayoutModelImpl
	extends BaseModelImpl<DEDataLayout> implements DEDataLayoutModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a de data layout model instance should use the <code>DEDataLayout</code> interface instead.
	 */
	public static final String TABLE_NAME = "DEDataLayout";

	public static final Object[][] TABLE_COLUMNS = {
		{"uuid_", Types.VARCHAR}, {"deDataLayoutId", Types.BIGINT},
		{"groupId", Types.BIGINT}, {"companyId", Types.BIGINT},
		{"userId", Types.BIGINT}, {"userName", Types.VARCHAR},
		{"createDate", Types.TIMESTAMP}, {"modifiedDate", Types.TIMESTAMP},
		{"deDataDefinitionId", Types.BIGINT}, {"dataLayoutKey", Types.VARCHAR},
		{"name", Types.VARCHAR}, {"description", Types.VARCHAR}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("uuid_", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("deDataLayoutId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("groupId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("deDataDefinitionId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("dataLayoutKey", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("name", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("description", Types.VARCHAR);
	}

	public static final String TABLE_SQL_CREATE =
		"create table DEDataLayout (uuid_ VARCHAR(75) null,deDataLayoutId LONG not null primary key,groupId LONG,companyId LONG,userId LONG,userName VARCHAR(75) null,createDate DATE null,modifiedDate DATE null,deDataDefinitionId LONG,dataLayoutKey VARCHAR(75) null,name STRING null,description STRING null)";

	public static final String TABLE_SQL_DROP = "drop table DEDataLayout";

	public static final String ORDER_BY_JPQL =
		" ORDER BY deDataLayout.deDataLayoutId ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY DEDataLayout.deDataLayoutId ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	public static final long COMPANYID_COLUMN_BITMASK = 1L;

	public static final long GROUPID_COLUMN_BITMASK = 2L;

	public static final long UUID_COLUMN_BITMASK = 4L;

	public static final long DEDATALAYOUTID_COLUMN_BITMASK = 8L;

	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
		_entityCacheEnabled = entityCacheEnabled;
	}

	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
		_finderCacheEnabled = finderCacheEnabled;
	}

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 */
	public static DEDataLayout toModel(DEDataLayoutSoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		DEDataLayout model = new DEDataLayoutImpl();

		model.setUuid(soapModel.getUuid());
		model.setDeDataLayoutId(soapModel.getDeDataLayoutId());
		model.setGroupId(soapModel.getGroupId());
		model.setCompanyId(soapModel.getCompanyId());
		model.setUserId(soapModel.getUserId());
		model.setUserName(soapModel.getUserName());
		model.setCreateDate(soapModel.getCreateDate());
		model.setModifiedDate(soapModel.getModifiedDate());
		model.setDeDataDefinitionId(soapModel.getDeDataDefinitionId());
		model.setDataLayoutKey(soapModel.getDataLayoutKey());
		model.setName(soapModel.getName());
		model.setDescription(soapModel.getDescription());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 */
	public static List<DEDataLayout> toModels(DEDataLayoutSoap[] soapModels) {
		if (soapModels == null) {
			return null;
		}

		List<DEDataLayout> models = new ArrayList<DEDataLayout>(
			soapModels.length);

		for (DEDataLayoutSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public DEDataLayoutModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _deDataLayoutId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setDeDataLayoutId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _deDataLayoutId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return DEDataLayout.class;
	}

	@Override
	public String getModelClassName() {
		return DEDataLayout.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<DEDataLayout, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		for (Map.Entry<String, Function<DEDataLayout, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<DEDataLayout, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply((DEDataLayout)this));
		}

		attributes.put("entityCacheEnabled", isEntityCacheEnabled());
		attributes.put("finderCacheEnabled", isFinderCacheEnabled());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<DEDataLayout, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<DEDataLayout, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(DEDataLayout)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<DEDataLayout, Object>>
		getAttributeGetterFunctions() {

		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<DEDataLayout, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static Function<InvocationHandler, DEDataLayout>
		_getProxyProviderFunction() {

		Class<?> proxyClass = ProxyUtil.getProxyClass(
			DEDataLayout.class.getClassLoader(), DEDataLayout.class,
			ModelWrapper.class);

		try {
			Constructor<DEDataLayout> constructor =
				(Constructor<DEDataLayout>)proxyClass.getConstructor(
					InvocationHandler.class);

			return invocationHandler -> {
				try {
					return constructor.newInstance(invocationHandler);
				}
				catch (ReflectiveOperationException roe) {
					throw new InternalError(roe);
				}
			};
		}
		catch (NoSuchMethodException nsme) {
			throw new InternalError(nsme);
		}
	}

	private static final Map<String, Function<DEDataLayout, Object>>
		_attributeGetterFunctions;
	private static final Map<String, BiConsumer<DEDataLayout, Object>>
		_attributeSetterBiConsumers;

	static {
		Map<String, Function<DEDataLayout, Object>> attributeGetterFunctions =
			new LinkedHashMap<String, Function<DEDataLayout, Object>>();
		Map<String, BiConsumer<DEDataLayout, ?>> attributeSetterBiConsumers =
			new LinkedHashMap<String, BiConsumer<DEDataLayout, ?>>();

		attributeGetterFunctions.put("uuid", DEDataLayout::getUuid);
		attributeSetterBiConsumers.put(
			"uuid", (BiConsumer<DEDataLayout, String>)DEDataLayout::setUuid);
		attributeGetterFunctions.put(
			"deDataLayoutId", DEDataLayout::getDeDataLayoutId);
		attributeSetterBiConsumers.put(
			"deDataLayoutId",
			(BiConsumer<DEDataLayout, Long>)DEDataLayout::setDeDataLayoutId);
		attributeGetterFunctions.put("groupId", DEDataLayout::getGroupId);
		attributeSetterBiConsumers.put(
			"groupId",
			(BiConsumer<DEDataLayout, Long>)DEDataLayout::setGroupId);
		attributeGetterFunctions.put("companyId", DEDataLayout::getCompanyId);
		attributeSetterBiConsumers.put(
			"companyId",
			(BiConsumer<DEDataLayout, Long>)DEDataLayout::setCompanyId);
		attributeGetterFunctions.put("userId", DEDataLayout::getUserId);
		attributeSetterBiConsumers.put(
			"userId", (BiConsumer<DEDataLayout, Long>)DEDataLayout::setUserId);
		attributeGetterFunctions.put("userName", DEDataLayout::getUserName);
		attributeSetterBiConsumers.put(
			"userName",
			(BiConsumer<DEDataLayout, String>)DEDataLayout::setUserName);
		attributeGetterFunctions.put("createDate", DEDataLayout::getCreateDate);
		attributeSetterBiConsumers.put(
			"createDate",
			(BiConsumer<DEDataLayout, Date>)DEDataLayout::setCreateDate);
		attributeGetterFunctions.put(
			"modifiedDate", DEDataLayout::getModifiedDate);
		attributeSetterBiConsumers.put(
			"modifiedDate",
			(BiConsumer<DEDataLayout, Date>)DEDataLayout::setModifiedDate);
		attributeGetterFunctions.put(
			"deDataDefinitionId", DEDataLayout::getDeDataDefinitionId);
		attributeSetterBiConsumers.put(
			"deDataDefinitionId",
			(BiConsumer<DEDataLayout, Long>)
				DEDataLayout::setDeDataDefinitionId);
		attributeGetterFunctions.put(
			"dataLayoutKey", DEDataLayout::getDataLayoutKey);
		attributeSetterBiConsumers.put(
			"dataLayoutKey",
			(BiConsumer<DEDataLayout, String>)DEDataLayout::setDataLayoutKey);
		attributeGetterFunctions.put("name", DEDataLayout::getName);
		attributeSetterBiConsumers.put(
			"name", (BiConsumer<DEDataLayout, String>)DEDataLayout::setName);
		attributeGetterFunctions.put(
			"description", DEDataLayout::getDescription);
		attributeSetterBiConsumers.put(
			"description",
			(BiConsumer<DEDataLayout, String>)DEDataLayout::setDescription);

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@JSON
	@Override
	public String getUuid() {
		if (_uuid == null) {
			return "";
		}
		else {
			return _uuid;
		}
	}

	@Override
	public void setUuid(String uuid) {
		_columnBitmask |= UUID_COLUMN_BITMASK;

		if (_originalUuid == null) {
			_originalUuid = _uuid;
		}

		_uuid = uuid;
	}

	public String getOriginalUuid() {
		return GetterUtil.getString(_originalUuid);
	}

	@JSON
	@Override
	public long getDeDataLayoutId() {
		return _deDataLayoutId;
	}

	@Override
	public void setDeDataLayoutId(long deDataLayoutId) {
		_deDataLayoutId = deDataLayoutId;
	}

	@JSON
	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		_columnBitmask |= GROUPID_COLUMN_BITMASK;

		if (!_setOriginalGroupId) {
			_setOriginalGroupId = true;

			_originalGroupId = _groupId;
		}

		_groupId = groupId;
	}

	public long getOriginalGroupId() {
		return _originalGroupId;
	}

	@JSON
	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		_columnBitmask |= COMPANYID_COLUMN_BITMASK;

		if (!_setOriginalCompanyId) {
			_setOriginalCompanyId = true;

			_originalCompanyId = _companyId;
		}

		_companyId = companyId;
	}

	public long getOriginalCompanyId() {
		return _originalCompanyId;
	}

	@JSON
	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		_userId = userId;
	}

	@Override
	public String getUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getUserId());

			return user.getUuid();
		}
		catch (PortalException pe) {
			return "";
		}
	}

	@Override
	public void setUserUuid(String userUuid) {
	}

	@JSON
	@Override
	public String getUserName() {
		if (_userName == null) {
			return "";
		}
		else {
			return _userName;
		}
	}

	@Override
	public void setUserName(String userName) {
		_userName = userName;
	}

	@JSON
	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		_createDate = createDate;
	}

	@JSON
	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		_modifiedDate = modifiedDate;
	}

	@JSON
	@Override
	public long getDeDataDefinitionId() {
		return _deDataDefinitionId;
	}

	@Override
	public void setDeDataDefinitionId(long deDataDefinitionId) {
		_deDataDefinitionId = deDataDefinitionId;
	}

	@JSON
	@Override
	public String getDataLayoutKey() {
		if (_dataLayoutKey == null) {
			return "";
		}
		else {
			return _dataLayoutKey;
		}
	}

	@Override
	public void setDataLayoutKey(String dataLayoutKey) {
		_dataLayoutKey = dataLayoutKey;
	}

	@JSON
	@Override
	public String getName() {
		if (_name == null) {
			return "";
		}
		else {
			return _name;
		}
	}

	@Override
	public String getName(Locale locale) {
		String languageId = LocaleUtil.toLanguageId(locale);

		return getName(languageId);
	}

	@Override
	public String getName(Locale locale, boolean useDefault) {
		String languageId = LocaleUtil.toLanguageId(locale);

		return getName(languageId, useDefault);
	}

	@Override
	public String getName(String languageId) {
		return LocalizationUtil.getLocalization(getName(), languageId);
	}

	@Override
	public String getName(String languageId, boolean useDefault) {
		return LocalizationUtil.getLocalization(
			getName(), languageId, useDefault);
	}

	@Override
	public String getNameCurrentLanguageId() {
		return _nameCurrentLanguageId;
	}

	@JSON
	@Override
	public String getNameCurrentValue() {
		Locale locale = getLocale(_nameCurrentLanguageId);

		return getName(locale);
	}

	@Override
	public Map<Locale, String> getNameMap() {
		return LocalizationUtil.getLocalizationMap(getName());
	}

	@Override
	public void setName(String name) {
		_name = name;
	}

	@Override
	public void setName(String name, Locale locale) {
		setName(name, locale, LocaleUtil.getSiteDefault());
	}

	@Override
	public void setName(String name, Locale locale, Locale defaultLocale) {
		String languageId = LocaleUtil.toLanguageId(locale);
		String defaultLanguageId = LocaleUtil.toLanguageId(defaultLocale);

		if (Validator.isNotNull(name)) {
			setName(
				LocalizationUtil.updateLocalization(
					getName(), "Name", name, languageId, defaultLanguageId));
		}
		else {
			setName(
				LocalizationUtil.removeLocalization(
					getName(), "Name", languageId));
		}
	}

	@Override
	public void setNameCurrentLanguageId(String languageId) {
		_nameCurrentLanguageId = languageId;
	}

	@Override
	public void setNameMap(Map<Locale, String> nameMap) {
		setNameMap(nameMap, LocaleUtil.getSiteDefault());
	}

	@Override
	public void setNameMap(Map<Locale, String> nameMap, Locale defaultLocale) {
		if (nameMap == null) {
			return;
		}

		setName(
			LocalizationUtil.updateLocalization(
				nameMap, getName(), "Name",
				LocaleUtil.toLanguageId(defaultLocale)));
	}

	@JSON
	@Override
	public String getDescription() {
		if (_description == null) {
			return "";
		}
		else {
			return _description;
		}
	}

	@Override
	public String getDescription(Locale locale) {
		String languageId = LocaleUtil.toLanguageId(locale);

		return getDescription(languageId);
	}

	@Override
	public String getDescription(Locale locale, boolean useDefault) {
		String languageId = LocaleUtil.toLanguageId(locale);

		return getDescription(languageId, useDefault);
	}

	@Override
	public String getDescription(String languageId) {
		return LocalizationUtil.getLocalization(getDescription(), languageId);
	}

	@Override
	public String getDescription(String languageId, boolean useDefault) {
		return LocalizationUtil.getLocalization(
			getDescription(), languageId, useDefault);
	}

	@Override
	public String getDescriptionCurrentLanguageId() {
		return _descriptionCurrentLanguageId;
	}

	@JSON
	@Override
	public String getDescriptionCurrentValue() {
		Locale locale = getLocale(_descriptionCurrentLanguageId);

		return getDescription(locale);
	}

	@Override
	public Map<Locale, String> getDescriptionMap() {
		return LocalizationUtil.getLocalizationMap(getDescription());
	}

	@Override
	public void setDescription(String description) {
		_description = description;
	}

	@Override
	public void setDescription(String description, Locale locale) {
		setDescription(description, locale, LocaleUtil.getSiteDefault());
	}

	@Override
	public void setDescription(
		String description, Locale locale, Locale defaultLocale) {

		String languageId = LocaleUtil.toLanguageId(locale);
		String defaultLanguageId = LocaleUtil.toLanguageId(defaultLocale);

		if (Validator.isNotNull(description)) {
			setDescription(
				LocalizationUtil.updateLocalization(
					getDescription(), "Description", description, languageId,
					defaultLanguageId));
		}
		else {
			setDescription(
				LocalizationUtil.removeLocalization(
					getDescription(), "Description", languageId));
		}
	}

	@Override
	public void setDescriptionCurrentLanguageId(String languageId) {
		_descriptionCurrentLanguageId = languageId;
	}

	@Override
	public void setDescriptionMap(Map<Locale, String> descriptionMap) {
		setDescriptionMap(descriptionMap, LocaleUtil.getSiteDefault());
	}

	@Override
	public void setDescriptionMap(
		Map<Locale, String> descriptionMap, Locale defaultLocale) {

		if (descriptionMap == null) {
			return;
		}

		setDescription(
			LocalizationUtil.updateLocalization(
				descriptionMap, getDescription(), "Description",
				LocaleUtil.toLanguageId(defaultLocale)));
	}

	@Override
	public StagedModelType getStagedModelType() {
		return new StagedModelType(
			PortalUtil.getClassNameId(DEDataLayout.class.getName()));
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			getCompanyId(), DEDataLayout.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public String[] getAvailableLanguageIds() {
		Set<String> availableLanguageIds = new TreeSet<String>();

		Map<Locale, String> nameMap = getNameMap();

		for (Map.Entry<Locale, String> entry : nameMap.entrySet()) {
			Locale locale = entry.getKey();
			String value = entry.getValue();

			if (Validator.isNotNull(value)) {
				availableLanguageIds.add(LocaleUtil.toLanguageId(locale));
			}
		}

		Map<Locale, String> descriptionMap = getDescriptionMap();

		for (Map.Entry<Locale, String> entry : descriptionMap.entrySet()) {
			Locale locale = entry.getKey();
			String value = entry.getValue();

			if (Validator.isNotNull(value)) {
				availableLanguageIds.add(LocaleUtil.toLanguageId(locale));
			}
		}

		return availableLanguageIds.toArray(
			new String[availableLanguageIds.size()]);
	}

	@Override
	public String getDefaultLanguageId() {
		String xml = getName();

		if (xml == null) {
			return "";
		}

		Locale defaultLocale = LocaleUtil.getSiteDefault();

		return LocalizationUtil.getDefaultLanguageId(xml, defaultLocale);
	}

	@Override
	public void prepareLocalizedFieldsForImport() throws LocaleException {
		Locale defaultLocale = LocaleUtil.fromLanguageId(
			getDefaultLanguageId());

		Locale[] availableLocales = LocaleUtil.fromLanguageIds(
			getAvailableLanguageIds());

		Locale defaultImportLocale = LocalizationUtil.getDefaultImportLocale(
			DEDataLayout.class.getName(), getPrimaryKey(), defaultLocale,
			availableLocales);

		prepareLocalizedFieldsForImport(defaultImportLocale);
	}

	@Override
	@SuppressWarnings("unused")
	public void prepareLocalizedFieldsForImport(Locale defaultImportLocale)
		throws LocaleException {

		Locale defaultLocale = LocaleUtil.getSiteDefault();

		String modelDefaultLanguageId = getDefaultLanguageId();

		String name = getName(defaultLocale);

		if (Validator.isNull(name)) {
			setName(getName(modelDefaultLanguageId), defaultLocale);
		}
		else {
			setName(getName(defaultLocale), defaultLocale, defaultLocale);
		}

		String description = getDescription(defaultLocale);

		if (Validator.isNull(description)) {
			setDescription(
				getDescription(modelDefaultLanguageId), defaultLocale);
		}
		else {
			setDescription(
				getDescription(defaultLocale), defaultLocale, defaultLocale);
		}
	}

	@Override
	public DEDataLayout toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, DEDataLayout>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		DEDataLayoutImpl deDataLayoutImpl = new DEDataLayoutImpl();

		deDataLayoutImpl.setUuid(getUuid());
		deDataLayoutImpl.setDeDataLayoutId(getDeDataLayoutId());
		deDataLayoutImpl.setGroupId(getGroupId());
		deDataLayoutImpl.setCompanyId(getCompanyId());
		deDataLayoutImpl.setUserId(getUserId());
		deDataLayoutImpl.setUserName(getUserName());
		deDataLayoutImpl.setCreateDate(getCreateDate());
		deDataLayoutImpl.setModifiedDate(getModifiedDate());
		deDataLayoutImpl.setDeDataDefinitionId(getDeDataDefinitionId());
		deDataLayoutImpl.setDataLayoutKey(getDataLayoutKey());
		deDataLayoutImpl.setName(getName());
		deDataLayoutImpl.setDescription(getDescription());

		deDataLayoutImpl.resetOriginalValues();

		return deDataLayoutImpl;
	}

	@Override
	public int compareTo(DEDataLayout deDataLayout) {
		long primaryKey = deDataLayout.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof DEDataLayout)) {
			return false;
		}

		DEDataLayout deDataLayout = (DEDataLayout)obj;

		long primaryKey = deDataLayout.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public boolean isEntityCacheEnabled() {
		return _entityCacheEnabled;
	}

	@Override
	public boolean isFinderCacheEnabled() {
		return _finderCacheEnabled;
	}

	@Override
	public void resetOriginalValues() {
		DEDataLayoutModelImpl deDataLayoutModelImpl = this;

		deDataLayoutModelImpl._originalUuid = deDataLayoutModelImpl._uuid;

		deDataLayoutModelImpl._originalGroupId = deDataLayoutModelImpl._groupId;

		deDataLayoutModelImpl._setOriginalGroupId = false;

		deDataLayoutModelImpl._originalCompanyId =
			deDataLayoutModelImpl._companyId;

		deDataLayoutModelImpl._setOriginalCompanyId = false;

		deDataLayoutModelImpl._setModifiedDate = false;

		deDataLayoutModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<DEDataLayout> toCacheModel() {
		DEDataLayoutCacheModel deDataLayoutCacheModel =
			new DEDataLayoutCacheModel();

		deDataLayoutCacheModel.uuid = getUuid();

		String uuid = deDataLayoutCacheModel.uuid;

		if ((uuid != null) && (uuid.length() == 0)) {
			deDataLayoutCacheModel.uuid = null;
		}

		deDataLayoutCacheModel.deDataLayoutId = getDeDataLayoutId();

		deDataLayoutCacheModel.groupId = getGroupId();

		deDataLayoutCacheModel.companyId = getCompanyId();

		deDataLayoutCacheModel.userId = getUserId();

		deDataLayoutCacheModel.userName = getUserName();

		String userName = deDataLayoutCacheModel.userName;

		if ((userName != null) && (userName.length() == 0)) {
			deDataLayoutCacheModel.userName = null;
		}

		Date createDate = getCreateDate();

		if (createDate != null) {
			deDataLayoutCacheModel.createDate = createDate.getTime();
		}
		else {
			deDataLayoutCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			deDataLayoutCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			deDataLayoutCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		deDataLayoutCacheModel.deDataDefinitionId = getDeDataDefinitionId();

		deDataLayoutCacheModel.dataLayoutKey = getDataLayoutKey();

		String dataLayoutKey = deDataLayoutCacheModel.dataLayoutKey;

		if ((dataLayoutKey != null) && (dataLayoutKey.length() == 0)) {
			deDataLayoutCacheModel.dataLayoutKey = null;
		}

		deDataLayoutCacheModel.name = getName();

		String name = deDataLayoutCacheModel.name;

		if ((name != null) && (name.length() == 0)) {
			deDataLayoutCacheModel.name = null;
		}

		deDataLayoutCacheModel.description = getDescription();

		String description = deDataLayoutCacheModel.description;

		if ((description != null) && (description.length() == 0)) {
			deDataLayoutCacheModel.description = null;
		}

		return deDataLayoutCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<DEDataLayout, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			4 * attributeGetterFunctions.size() + 2);

		sb.append("{");

		for (Map.Entry<String, Function<DEDataLayout, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<DEDataLayout, Object> attributeGetterFunction =
				entry.getValue();

			sb.append(attributeName);
			sb.append("=");
			sb.append(attributeGetterFunction.apply((DEDataLayout)this));
			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		Map<String, Function<DEDataLayout, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			5 * attributeGetterFunctions.size() + 4);

		sb.append("<model><model-name>");
		sb.append(getModelClassName());
		sb.append("</model-name>");

		for (Map.Entry<String, Function<DEDataLayout, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<DEDataLayout, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("<column><column-name>");
			sb.append(attributeName);
			sb.append("</column-name><column-value><![CDATA[");
			sb.append(attributeGetterFunction.apply((DEDataLayout)this));
			sb.append("]]></column-value></column>");
		}

		sb.append("</model>");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, DEDataLayout>
			_escapedModelProxyProviderFunction = _getProxyProviderFunction();

	}

	private static boolean _entityCacheEnabled;
	private static boolean _finderCacheEnabled;

	private String _uuid;
	private String _originalUuid;
	private long _deDataLayoutId;
	private long _groupId;
	private long _originalGroupId;
	private boolean _setOriginalGroupId;
	private long _companyId;
	private long _originalCompanyId;
	private boolean _setOriginalCompanyId;
	private long _userId;
	private String _userName;
	private Date _createDate;
	private Date _modifiedDate;
	private boolean _setModifiedDate;
	private long _deDataDefinitionId;
	private String _dataLayoutKey;
	private String _name;
	private String _nameCurrentLanguageId;
	private String _description;
	private String _descriptionCurrentLanguageId;
	private long _columnBitmask;
	private DEDataLayout _escapedModel;

}